$( document ).ready()

/*
var german_text = [Mehr, als, "46.000", Erfindungen, meldeten, die, Deutschen, vergangenes, Jahr, beim, Patent, und, 
Markenamt, an, "1159", davon, stammen, aus, Berlin, und, Brandenburg, Das, Buch, Genial, Erfindungen, aus, Berlin, 
und, Brandenburg, fasst, von, A, wie, Augenspiegel, bis, Z, wie, Zucker, aus, Rüben, die, Entdeckungen, aus, der, 
Region, seit, dem, "18", Jahrhundert, zusammen, Eine, Spurensuche, Der, Pappteller, Da, Papier, Mitte, des, "19", 
Jahrhunderts, ein, teures, Gut, war, versuchte, man, es, so, häufig, wie, möglich, wieder, zu, verwenden, Händler, 
wickelten, alles, egal, ob, Fisch, Fleisch, oder, Früchte, "in", Buchseiten, Briefe, und, Zeitungspapier, Das, 
beleidigte, nicht, nur, die, schreibende, Zunft, Heinrich, Heine, klagte, Ach, Mein, Buch, der, Lieder, wird, der, 
Krautkrämer, zu, Tüten, verwenden, um, Kaffee, oder, Schnupftabak, darin, zu, schütten, sondern, verpasste, den, 
Lebensmitteln, auch, eine, unappetitliche, Druckerschwärze, Panade, Als, die, Medizin, aufdeckte, dass, der, Verzehr,
von, Druckerschwärze, zudem, nicht, besonders, gesundheitsfördernd, ist, kam, einem, Buchbinder, schließlich, eine, Idee, 
Der, Luckenwalder, Hermann, Henschel, experimentierte, "in", seiner, Werkstatt, so, lange, mit, Kartonmaterialien, herum, 
bis, es, ihm, "1867", schließlich, gelang, den, weltersten, Pappteller, zu, pressen, Schneeweiß, mit, gewellten, Kanten, 
ganz, so, wie, wir, ihn, noch, heute, als, Würstchenuntersatz, kennen, Der, "23", Jährige, gründete, schließlich, eine, 
Papierwarenfabrik, und, sein, Pappteller, ging, "in", Serie, Ein, voller, Erfolg, Henschels, Firma, besteht, als, 
Luckenwalder, Tüten, und, Papptellerfabrik, noch, bis, heute, Das, nahtlose, Kondom, Tierdärme, Fischblasen, Leinenhüllen, 
Ölpapier, die, Liste, der, früher, als, Kondom, verwendeten, Materialien, ist, lang, Kein, Wunder, schließlich, gab, es, die, 
Lümmeltüten, schon, bei, den, alten, Ägyptern, Ihr, heutiger, Name, geht, so, vermutet, man, wenigstens, auf, den, Hofarzt, 
des, englischen, Königs, Karl II, zurück, Oberst, Dr, Condom, soll, seinem, hoheitlichen, Patienten, Hammeldärme, als, 
Empfängnisschutz, verordnet, haben, Appetitlich, wurde, das, Kondom, erst, durch, Charles, Goodyear, Der Chemiker, erfand, 
"1839", auch, das, Gummi, Kondom, Es, war, zwei, Millimeter, dick, und, trug, eine, dicke, Längsnaht, die, nicht, nur, den, 
jüdischen, Berliner, Julius, Fromm, störte, "1914", betrieb, Fromm, "in", einem, Hinterhof, "in", Prenzlauer, Berg, ein, 
Werkstattgeschäft, für, Parfümerie, und, Gummiwaren, Dort, gelang, es, ihm, mit, einem, "in", Gummilösung, getauchten, 
Glaskolben, das, erste, nahtlose, Kondom, herzustellen, Im, Jahr, "1916", ging, es, unter, dem, Namen, Fromms, Act, auf, 
den, Markt, Bis, heute, werden, Kondome, unter, dem, Markenamen, Fromm, produziert, Ohropax, Holz, Metall, oder, Hartgummi, 
die, Berliner, steckten, sich, zu, Beginn, des, Maschinenzeitalters, so, einiges, "in", die, Ohren, um, sich, vor, dem, 
neuen, Industrielärm, zu, schützen, Die, harten, Gegenstände, im, Gehörgang, waren, dabei, aber, nur, minimal, 
angenehmer, als, die, Geräuschbelästigung, Maximilian, Negwer, aus, Schlesien, betrieb, Anfang, des, "20", Jahrhunderts, 
eine, Fabrik, "in", Berlin, Ob, Puder, Parfüms, oder, Frost, und, Schnupfencremes, die Produktpalette, seiner, kosmetisch, 
pharmazeutischen, Spezialitätenfabrik, erschien, ihm, nie, vollständig, Inspiriert, von, Homers, Odysseus, der, die, Ohren, 
seiner, Männer, mit, Wachs, verstopfen, ließ, um, sie, vor, dem, verlockenden, Sirenengesang, zu, schützen, kam, er, schließlich, 
auf, die, Idee, einen, neuen, angenehmeren, Lärmstopp, zu, entwickeln, Aus, einer, Mischung, aus, Wachs, Vaseline, und, 
Baumwollwatte, presste, er, kleine, Lärmstopp, Kügelchen, die, bequem, zu, tragen, waren, und, sich, ohne, Rückstände, wieder, 
entfernen, ließen, Negwer, nannte, sie, Ohropax, Eine, Wortschöpfung, aus, Ohr, und, dem, lateinischen, Wort, Pax, für, Frieden, 
Ironischerweise, machte, der, Ohrenfrieden, aber, erst, durch, den, Krieg, richtig, Karriere, Von, "1914", bis, "1918", wurde, er, 
an, der, deutschen, Front, verteilt, um, den, Soldaten, im, Kugelgewitter, das, Gehör, zu, schützen, Das FaxGerät, Als, der, 
Eggmühler, Diplomingenieur, Rudolf, Hell, Ende, der, "20er-Jahre", das, Auto, seiner, Mutter, erbt, verkauft, er, es, sofort,
en, Erlös, nutzt, er, als, Startkapital, um, "in", Babelsberg, ein, "Elektrotechnik-Unternehmen", zu, gründen, Hell, war, seit, 
seiner, Kindheit, von, den, Kommunikationsmitteln, der, Moderne, begeistert, Er, wollte, nur, eins, Den, Fortschritt, weiter, 
vorantreiben, Babelsberg, schien, Hell, als, idealer, Standort, da, im, benachbarten, Berlin, die, meisten, Behörden, 
Forschungsgremien, und, Unternehmen, der, Branche, angesiedelt, waren, Und, schon, kurz, nach, Umzug, und, Firmengründung, 
stellte, der, Ingenieur, schließlich, seinen, "Hell-Schreiber", vor, ein, "Fax-Gerät", Zugegeben, die, Idee, eines,  
schreibenden, Telegrafen, war, nicht, neu, aber, erst, der, "Hell-Schreiber", war, so, robust, schnell, und, verlässlich,
dass, er, rundum, alltagstauglich, war, Denn, wenn, Sender, und, Empfänger, nicht, synchron, liefen, wurde, die, Nachricht, 
zwar, schief, aber, trotzdem, lesbar, übermittelt, "1931", gingen, die, "Hell-Schreiber", bei, Siemens, "in", Massenproduktion, 
Seine, Ideen, kamen, dem, "2002", gestorbenen, Hell, nach, eigener, Aussage, übrigens, beim, Rasieren, Ein Trick, der, offenbar, 
recht, häufig, funktionierte, Hell, meldete, zeit, seines, Lebens, insgesamt, "131", Patente, an, Die, Spalttablette, Sagen, 
Se, mal, Meester, "könn'", Se, en, Loch, "in", ne, Tablette, machen, oder, ne, Kerbe, oder, sonst, wat, det, man, im, Dunkeln, 
fühlen, kann, wat, es is, das, soll, Kaufmann, Leo, Maximilian, Baginski, im, Jahr, "1932", zu, seinem, Pharmazeuten, gesagt,
haben, und, kurz, darauf, soll, sie, geboren, worden, sein, die, Spalttablette, Ihre, chemische, Zusammensetzung, war, die, 
einer, Kopfschmerztablette, Diese, Tablette, war, aber, "1932", bereits, erfunden, und, somit, nicht, patentwürdig, Aber, das, 
Erscheinungsbild, der, Berliner, Tablette, das, war, völlig, neu, und, ließ, sich, somit, als, "Wort-Bild-Warenzeichen", patentieren, 
Ab, dem, "21", Juni, des, gleichen, Jahres, war, sie, "in", allen, Berliner, Apotheken, erhältlich, und, kurz, darauf, vergriffen, 
Zehn, Jahre, später, wurde, sie, mit ,einem, "1,37", Millionen, Reichsmark, großen, Werbeetat, beworben, Die, unter, Migräne, leidende, 
Hausfrau, der, verkaterte, Gatte, der, Kriegsversehrte, kaum, eine, Zielgruppe, wurde, ausgelassen, Der, Schirm, Schirme, schützen, 
vor, Bankrott, vor, Sonne, und, vor, allem, vor, Regen, Es, gibt, sie, seit, Tausenden, von, Jahren, aber, erst, Ende, des, "17", 
Jahrhunderts, entdeckte, die, adelige, Damenwelt, das, ehemalige, Hoheitssymbol, als, Sonnenschutz, Mit, Beginn, des, "19", 
Jahrhunderts, wird, das, mobile, Faltdach, schließlich, uch, als, Regenunterschlupf, genutzt, Doch, das, mit, Leinwand, oder, Baumwolle, 
bespannte, Holz, oder, Messinggestell, war, nichts, für, schmale, Ärmchen, Ein, Schirm, wog, damals, um, die, fünf, Kilogramm, Der, 
Engländer, Samuel, Fox, entwarf, Mitte, des, "19", Jahrhunderts, ein, Stahlgestell, das, "in", einem, Bambusfutteral, verschwinden, und, 
somit, bei, Sonnenschein, zum, Spazierstock, werden, konnte, Richtig, handlich, wurde, der, Regenschutz, aber, erst, "in", Berlin, Der,
Bergassessor, Hans, Haupt, ärgerte, sich, aufgrund, seiner, Kriegsverletzung, so, sehr, über, die, Sperrigkeit, des, Langschirms, dass, er, 
sich, bereits, "1914", das, Patent, für, einen, Schirm, den, man, teleskopartig, ineinanderschieben, kann, schützen, ließ, "Der Ur-Knirps", 
Der, kleinste, Schirm, der, Welt, wird, heute, "in", mehr, als, "120", Ländern, verkauft, Die, Pinnnadel, Johann, Kirsten, war, Uhrmacher, und, 
lebte, um, "1900", Viel, mehr, kann, man, heute, nicht, mit, Sicherheit, über, ihn, sagen, Aber, er, muss, wohl, ein, Genie, mit, Tausenden, von,
kleinen, nützlichen, Einfällen, gewesen, sein, Und, vermutlich, lagen, all, diese, Einfälle, notiert, auf, kleinen, Papierschnipseln, "in", seinem,
Erfinderbüro, herum, So, lange, bis, ihn, die, Ordnungswut, packte, Er, brauchte, Überblick, So, muss, ihm, die, Idee, zur, Pinnnadel, 
gekommen, sein, Ein, kleiner, spitzer, Stift, mit, einer, Schutzkappe, die, ein, verletzungsfreies, Anfassen, garantierte, Johann, 
Kirsten, verkaufte, die, ersten, Heftzwecken, "in", kleinen, Tütchen, Der, richtige, Geschäftssinn, fehlte, ihm, aber, Er, ließ, 
sich, die, Rechte, an, der, Pinnnadel, für, eine, schmale, Hand, von, dem, Kaufmann, Otto, Lindstedt, abkaufen, Dieser, ließ, sich,
die, Heftzwecke, "1904", patentieren, und, gab, sie, "in", Produktion, Das, Teelicht, Heute, wärmt, es, unsere, Teekannen, sorgt,
für, beschauliches, Licht, "in", der, Weihnachtszeit, und, verströmt, ganzjährige, Düfte, von, Apfel, bis, Zimt, das, Teelicht, 
Seinen, Ursprung, hat, es, vermutlich, "in", den, Schützengräben, des, Ersten, Weltkrieges, Eine, flache, Schale, von, fünf, bis, 
acht, Zentimeter, Durchmesser, aus, wasserabweisender, Pappe, gefüllt, mit, fettigen, Schlachtabfällen, und, einem, Docht, fungierte,
hier, als, Notlicht, Benannt, wurde, das, Teelicht, zunächst, nach, der, Obersten, Heeresleitung, Generalfeldmarschall, Paul, von, 
Hindenburg, Und, gestunken, hat, es, Als, man, nach, dem, Krieg, die, Schälchen, als, Lichtquelle, "in", der, Stube, aufstellen, wollte,
gab, man, "in", Berlin, deswegen, Paraffine, und, Stearine, hinzu, Nach, dem, Zweiten, Weltkrieg, nutzte, man, die, neu, entdeckten, 
wärmenden, Qualitäten, des, Lichtes, nicht, mehr, nur, für, die, Hände, sondern,  für, den, Nachmittagstee, Das, Licht, hatte, seinen,
Weg, ins, Stövchen, gefunden, und, war, zum, Teelicht, geworden, Die, Litfaßsäule, Am, "1", Juli, "1855", kehrte, die, Ordnung, "in", 
Berlin, ein, Über, Nacht, verschwanden, alle, wild, plakatierten, Bekanntmachungen, und, Werbezettel, von, Häusern, Bäumen, und, Zäunen, 
Die, Berliner, trauten, ihren, Augen, nicht, Akkurat, aufgereiht, klebten, die, Informationen, an, diesem, Morgen, an, "100", neuen,
Säulen, und, "50", Pumpenumhüllungen, Der, Verleger, und, Druckereibesitzer, Ernst, Litfaß, liebte, die, preußische, Ordnung, und, 
überzeugte, den, Polizeipräsidenten, Karl, Ludwig, Friedrich, von, seinen, runden, Errichtungen, Sie, sollten, der, unkontrollierten, 
"Anschlagwut",  Herr, werden, Der, Verleger, wurde, kurzerhand, zum, "Säulenheiligen", ernannt, Heute, gibt, es, über, "50.000", 
Litfaßsäulen, "in", Deutschland, ]; */


var english_text = [More, than, "46,000", inventions, registered, by, the, Germans, last, year, at, the, and,
Trademark, Office, at, "1159", "of", which, come, from, Berlin, and, Brandenburg, the, book, Awesome, Inventions, from, Berlin,
and, Brandenburg, summarizes, from, A, such, as, ophthalmoscope, until, Z, as, sugar, from, beets, the, discoveries, from, the,
Region, since, the, "18", century, together, one, trace, the, paper plate, da, paper, middle, "of", "19",
Century, one, expensive, good, was, tried, one, it, as, often, as, possible, again, to, use, dealer,
wrapped, all, no matter, whether, fish, meat, or, fruits, "in," pages, letters, and, newsprint, that,
insulted, not, only, the, writing, guild, Heinrich, Heine, complained, oh, my, book, who, songs, will, who,
Herb, to, bags, use, to, coffee, or, snuff, "in", to, pour, but, missed, the,
Food, also, an, unappetizing, printing ink, breading, as, the, medicine, revealed, that, the, eating,
"of", "printing-ink", moreover, not, especially, "health-promoting", is, came, a, bookbinder, finally, an, idea,
The, Luckenwalder, Hermann, Henschel, experimented, "in," his, workshop, so, long, with, cardboard materials, around,
until, it, succeeded, "1867", finally, the, "world-first", paper plate, to, press, "snow-white", with, wavy, edges,
quite, as, we, him, still, today, know, as, "sausage-substitute", The, "23", "year-old", founded, finally, one,
Paper factory, and, be, paper plate, went, "in," series, one, full, success, Henschels, company, exists, as,
Luckenwalder, bags, and, paper plate factory, still, until, today, that, seamless, condom, animal casings, fish bubbles, linen covers,
Oil paper, the, list, the, earlier, than, condom, used, materials, is, long, no, miracle, finally, gave, it, the,
Lümmeltüten, already, at, the, old, egyptians, their, today, name, goes, so, suspects, one, at least, on, the, Hofarzt,
"of" the English King, Charles II, Colonel, Dr, Condom, is said to, his, sovereign, patient, mutton, as,
Contraception, prescribed, have, appetizing, was, the, condom, first, by, Charles, Goodyear, The Chemist, invented,
"1839", too, that, rubber, condom, it, was, two, millimeters, thick, and, wore, a, thick, longitudinal seam, the, not, only, the,
Jewish, Berliner, Julius, Fromm, disturbed, "1914", operated, Fromm, "in", one, backyard, "in", Prenzlauer, mountain, one,
Workshop shop, for, perfumery, and, rubber goods, There, managed, it, with, a, "in", rubber solution, dipped,
Flask, the, first, seamless, condom, manufacture, "in", year, "1916", went, it, under, the, name, fromms, act, on,
the, market, until, today, condoms, under, the, brand name, pious, produces, earplugs, wood, metal, or, hard rubber,
the, Berliner, stuck, to, the, beginning, "of", the, machine age, so, some, "in", the, ears, to, before, the,
"new", industrial, noise, protect, the, hard, objects, "in", ear canal, were, at, but, only, minimal,
more pleasant than, the noise nuisance, Maximilian, Negwer, from, Silesia, operation, beginning, "of", "20", century,
a, factory, "in," berlin, ob, powder, perfumes, or, frost, and, colds, the product range, its, cosmetically,
pharmaceutical, specialty factory, appeared to him, never, completely, Inspired, by, Homer, Odysseus, the, the, ears,
his, men, with, wax, clog, "let", to, before, the, seductive, siren, to, protect, came, he, finally,
on, the, idea, a, "new", more enjoyable, noise stop, develop, off, a, blend, off, wax, vaseline, and,
Cotton, pressed, he, small, noise stop, beads, the, convenient, to, carry, and, themselves, without, arrears, again,
remove, "let", negwer, named, her, earplug, one, word, out, ear, and, the, latin, word, pax, for, peace,
Ironically, made, the, "ear-peace", but, only, by, the, war, right, career, "of", "1914", until, "1918", he,
at, the, german, front, distributed, to, the, soldiers, "in", ball thunderstorm, the, hearing, the, protect, the, faxmachine, as, the,
Eggmühler, graduate engineer, Rudolf Hell, the end, the '20s', the, car, his, mother, inherits, sells, he, it, immediately,
He uses, as, "start-up" capital, to, "in", Babelsberg, an, "electrical engineering company" to start, Hell, was, since,
his, childhood, "of", the, means "of" communication, the, modern, enthusiastic, he, wanted, only, one, the, further,
Babelsberg, seemed bright, as, ideal, location, because, "in", neighboring, Berlin, the, most, authorities,
Research committees, and, companies, industry, were located, And, already, shortly, after, relocation, and, company formation,
the, engineer, finally, his, "Hell-Schreiber," a, "fax-machine," admitted, the, idea, one,
writing, telegraph,was, not, "new", but, first, the, "Hell-Scribe", was, so, robust, fast, and, reliable, that, he, all around, was 
fit for daily use, because, if, transmitter, and, receiver, not, synchronous, ran, was, the, message, though, wrong, but, 
nevertheless, readable, transmitted, "1931", the, "Hell-Schreiber", went, Siemens, "in", "mass-production", Seine, Ideas, came,
the, "2002", deceased, Hell, after, own, statement, by the way, when, shaving, A trick that, apparently, right, often, worked, 
Hell, reported, time, his, life, "in" total , "131", patents, on, the, "split-tablet", say, se, times, meester, "may," se, en, hole, 
"in," ne, tablet, or, ne, notch, or, otherwise, wat, det, one, "in", dark, feel, can, wat, it is, that, shall, merchant, Leo, Maximilian,
Baginski, "in", year, "1932", to, his, pharmacist, have said and, "in" short, "it's" supposed to be, her, born, cleavage, her, chemical, 
composition, that, a, headache This tablet was, but was, "1932" already, invented, and, thus, not, patentable, but, the, appearance, 
the, Berliner, tablet, that, was, completely, "new", and, "let", Thus, as the "Word Image Trademark" patent, the "21" June "of" the same year
was available to them "in" "all", Berliner, pharmacies, and, short, on, out "of" print, ten, years, later, she, with, one, "1,37", 
millions, Reichsmark, big, publicity, advertised, the, under, migraine, suffering, housewife, who, hungover, Spouse, the, 
warred, barely, a, target, became, hilarious, the, screen, screens, protect, front, bankrupt, before, sun, and, before, all,
before, rain, there, gives, them, since, Thousands "of" years, but, only, end, "of", "17", century, discovered, the, aristocratic, 
ladies, the, former, sovereignty symbol, as, sunshade, with, beginning, "of", "19", century, The mobile, folding roof, eventually,
as, rain shelter is used t, but, that, with, canvas, or, cotton, stringed, wood, or, brass frame, was, nothing, for, narrow, 
arm, a, screen, weighed, then, to, the, five, kilogram, the, Englishman Samuel Fox designed the middle "of" the "19" century steel 
frame which would disappear into "a" bamboo fodder and, thus, become a sunshine cane, could, Right, handy, was, the, rain, but, first,
"in," Berlin, the, Bergassessor, Hans, chief, annoyed, himself, because "of", his, war, injury, so, very, about, the, bulkiness, "of", 
Langschirms, that, he, himself, already, "1914", the patent, for, one, telescope, telescope, can, protect, "let", "The primal-tot", The, 
smallest, screen The world will be sold today "in" "more" than "120" countries that were Pin, Johann, Kirsten, watchmaker, and, lived around,
"1900", much, more , can, one, today, not, with, security, over, him, say, But, he, must, well, e "in", genius, with, thousands, "of", small, 
useful, ideas, been, and, presumably, lay, all, these, ideas, recorded, on, small, papercuts, "in," his, inventor, around, So, long, until, 
he, the, Ordnungswut, packed, He, needed, overview, So, must, him, the, idea, to, Pinnnadel, come, be, a, smaller, sharpener, pin, with, a, 
Cap, the, an, injury, touch, guaranteed, Johann, Kirsten, sold, the, first, thumbtacks, "in," small, sachets, the, correct, business acumen, 
lacking, him, but, he, "let", himself, The "right-to-the, pin-needle", for, a, narrow, hand, "of", the, merchant, Otto, Lindstedt, Shop, This, Let, 
The, Thumbtack, "1904," patent, and, gave, she, "in," production, tealight, today, warm, it, our, teapots, ensures, contemplative, light, "in,"
the, christmas, and, exudes, "year-round", scents, "of", apple, until, cinnamon, that, tealight, its, origin, ha t, it, probably, "in", the, trenches,
"of", the, first, world war, one, flat, shell, "of", five, to, eight, centimeters, diameter, "of", "water-repellent, cardboard", filled, with, greasy, 
Slaughterhouse, and, one, wick, acted, here, as, emergency, named, became, the, tealight, first, after, the, supreme, command, field marshal, 
Paul, von, Hindenburg, and, stink, has, it, As one wanted to put up the "dish" as the light source "in" the parlor, one gave "man in Berlin,"
because "of" that, paraffins, and, stearines, After, the, second, world war, used, one, the, "new", discovered, warming, qualities, "of", light, not, 
more, only, for, the, hands, but, for, the, afternoon tea, the, light, had found his way into the warmer, and had become, to the tealight, 
the Litfaßsäule, am, "1", July, "1855", returned, the, order, "in", Berlin, one, over, night, disappeared, all, wild, placarded, Bekan 
preparations, and, billboards, "of", houses, trees, and, Fences, the, Berliner, dared, their, eyes, not, Akkurat, strung, pasted, the, 
information, at, "this", morning, at, "100", "new", columns, and, "50", pump shrouds, the, Publisher, and, printer, Ernst, Litfaß, loved, 
the, Prussian, order, and, convinced, the, Police, President, Karl, Ludwig, Frederick, "of", his, round, establishments, you, the, uncontrolled,
"rage ", "Mr.", will, the, publisher, was appointed, without further ado, to," pillar-saint ", Today, there, about," 50.000 ", Litfaßsäulen,
" in ", Germany,];   


german_text.forEach(function(item, index, array) {
  console.log(item, index);
});

english_text.forEach(function(item, index, array) {
  console.log(item, index);
});